# Generated by Django 3.0.7 on 2020-09-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_defect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='reviewers_score',
        ),
    ]
