# Generated by Django 3.0.7 on 2020-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_defect', '0003_main_table_reviewers_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='review_closed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
