# Generated by Django 3.0.7 on 2020-09-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_defect', '0004_main_table_review_closed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.TextField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
